#!/usr/bin/env bash
set -e

datamodel-codegen \
    --url https://api.neris.fsri.org/v1/openapi.json \
    --input-file-type openapi \
    --output src/neris_api_client/models.py \
    --output-model-type pydantic_v2.BaseModel
